# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.token_generator:
        class: AppBundle\Service\TokenGenerator
        arguments: ["@doctrine"]
    app.email_recuperacao_senha:
        class: AppBundle\Service\EmailRecuperacaoSenha
        arguments: ["@mailer", "@router", "@templating"]
    app.redefinidor_senha:
        class: AppBundle\Service\RedefinidorDeSenha
        arguments: ["@security.password_encoder"]